api/urls.py
#urls de la aplicacion de docentes

from django.urls import path
from api import views as v
from docentes import views



#ponemos el nombre de la app para cuando mandemos llamar a las url poner docentes.urls
app_name = 'api'
urlpatterns = [

    path('planeaciones',v.Planeacion_APIView.as_view(),name='planeaciones'),
    path('planeaciones/<str:pk>',v.Planeacion_APIView.as_view(),name='planeaciones'),
    path('clonarPlaneacion',v.PlaneacionClonarView.as_view(),name='clonarPlaneacion'),

    path('buscarPlaneacion',v.Planeacion_APIViewFree.as_view(),name='buscarPlaneacion'),
    path('buscarPlaneacion/<str:titulo>',v.Planeacion_APIViewFree.as_view(),name='buscarPlaneacion'),

    path('favoritos',v.Favorito_APIView.as_view(),name='favoritos'),#para los favoritos
    path('favoritos/<str:pk>',v.Favorito_APIView.as_view(),name='favoritos'),#para los favoritos

    path('actividades',v.Actividad_APIView.as_view(),name='actividades'),#para los favoritos
    path('actividades/<str:pk>',v.Actividad_APIView.as_view(),name='actividades'),#para los favoritos
    path('actividadesFree',v.Actividad_APIView.as_view(),name='actividadesFree'),#para los favoritos sin logearse
    path('actividadesFree/<str:pk>',v.Actividad_APIView.as_view(),name='actividadesFree'),#para los favoritos sin logearse

    path('obtenerComentarios',v.Comentario_APIViewFree.as_view(),name='obtenerComentarios'),
    path('obtenerComentarios/<str:pk>',v.Comentario_APIViewFree.as_view(),name='obtenerComentarios'),
    path('comentarios',v.Comentario_APIView.as_view(),name='comentarios'),
    path('comentarios/<str:pk>',v.Comentario_APIView.as_view(),name='comentarios'),


]

docentes/urls.py
#urls de la aplicacion de docentes

from django.contrib import admin
from django.urls import path
from docentes import views

#ponemos el nombre de la app para cuando mandemos llamar a las url poner docentes.urls
app_name = 'docentes'

urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login_user,name='login'),
    path('registrarse',views.registrar_usuario,name='registrar_usuario'),
    path('cerrarsesion',views.cerrar_sesion,name='cerrar_sesion'),
    path('actualizarPassword',views.actualizarPassword,name='actualizarPassword'),
    path('actualizarUsuario',views.actualizarUsuario,name='actualizarUsuario'),
    path('crearPlaneacion',views.crearPlaneacion,name='crearPlaneacion'),
    path('favoritos',views.favoritos,name='favoritos'),
    path('misPlaneaciones',views.misPlaneaciones,name='misPlaneaciones'),
    path('perfil',views.perfil,name='perfil'),

]

planeacion_docente/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('docentes.urls')),
    path('api/',include('api.urls'))
]

docentes/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Customer(User):
    class meta:
        proxy=True
    
    
class Planeacion(models.Model):
    grado = models.IntegerField(null=False)
    fecha_de_finalizacion = models.DateField(null=False)
    titulo = models.CharField(max_length=60,null=False)
    tema = models.CharField(max_length=60,null=False)
    fecha_de_inicio=models.DateField(null=False)
    id_usuario = models.ForeignKey(User,on_delete=models.CASCADE,blank=False)
    anonima = models.BooleanField(default=False)
    finalizada = models.BooleanField(default=False)
    observaciones = models.TextField(null=True,blank=True)
    #blank true indica que si se puede dejar vacio
    def __str__(self) -> str:
        return self.titulo
    def nombreUsuario(self):
        return User.objects.get(id=self.id_usuario).username


class Actividad(models.Model):
    titulo=models.CharField(max_length=50,null=False)
    fecha_de_inicio=models.DateField(null=False)
    descripcion=models.TextField(null=True,blank=True)
    id_planeacion=models.ForeignKey(Planeacion,on_delete=models.CASCADE)
    finalizada = models.BooleanField(default=False)
    def __str__(self) -> str:
        return self.titulo

##class Rating(models.Model):


class Comentario(models.Model):
    id_usuario=models.ForeignKey(User,on_delete=models.CASCADE)
    id_planeacion=models.ForeignKey(Planeacion,on_delete=models.CASCADE)
    comentario=models.TextField(null=True,blank=True)
    def __str__(self)->str:
        return self.comentario

   
    


class Favorito(models.Model):
    id_usuario=models.ForeignKey(User,on_delete=models.CASCADE)
    id_planeacion=models.ForeignKey(Planeacion,on_delete=models.CASCADE)
    fecha_agregad=models.DateField(auto_now_add=True)
    def __str__(self) -> str:
        return str(self.pk)+' '+str(self.id_usuario)+' '+str(self.id_planeacion)

docentes/views.py
from traceback import print_tb
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import  login_required
from rest_framework.authtoken.models import Token
import re
# Create your views here.



 

#@login_required(login_url='docentes:login')
def index(request):
    return render(request,'docentes/index.html',{})

@login_required(login_url='docentes:login')
def crearPlaneacion(request):
    return render(request,'docentes/crear_planeacion.html',{})

@login_required(login_url='docentes:login')
def favoritos(request):
    return render(request,'docentes/favoritos.html',{})

@login_required(login_url='docentes:login')
def misPlaneaciones(request):
    return render(request,'docentes/tus_planeaciones.html',{})

@login_required(login_url='docentes:login')
def perfil(request):
    return render(request,'docentes/perfil_usuario.html',{})

@login_required(login_url='docentes:login')
def actualizarPassword(request):
    if request.method == 'POST':
        user=User.objects.get(id=request.user.id)
        if request.POST['password'] == request.POST['password2'] and request.POST['password']!='' and request.POST['password2']!='':
            user.set_password(request.POST['password'])
            user.save()
            logout(request)
            return redirect('docentes:login')
        elif request.POST['password']!=request.POST['password2'] or request.POST['password2']!=request.POST['password']:
            return render(request,'docentes/actualizacion_password.html',{'password_distintos':'Contrasena no valida'})
   
        elif request.POST['password']=='' and request.POST['password2']=='' or request.POST['password']=='' or request.POST['password2']=='':
            return render(request,'docentes/actualizacion_password.html',{'password_vacio':'Campos Sin Implementar'})
    
    return render(request,'docentes/actualizacion_password.html',{})
    
@login_required(login_url='docentes:login')  
def actualizarUsuario(request):
    if request.method == 'POST':
        email = request.POST['email']
        name = request.POST['name']
        user = User.objects.get(id=request.user.id)
        allUser=User.objects.all()
        for user_ahutenticate in allUser:
            if user_ahutenticate.username==request.POST['name']:
                return render(request,'docentes/actualizacion_informacion.html',{'noUser':'Usuario ya existente'})
        if email=='' and name!='':
            user.username=name
            user.save()
            return render(request,'docentes/index.html',{})
        elif email!='' and name=='':
            user.email=email
            user.save()
            return render(request,'docentes/index.html',{})
       
        elif  email=='' and name=='':
            return render(request,'docentes/actualizacion_informacion.html',{'noAcualizado':'No se actualiza ningun dato'})
        if len(name)!=0 and len(email)!=0:
            user.username = name
            user.email = email
            user.save()
            return redirect('docentes:index')
    return render(request,'docentes/actualizacion_informacion.html',{'mensajeError' : 'Rellene los campos para hacer el cambio'})
    
#para logiar al usuario
def login_user(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('docentes:index')
        return render(request,'docentes/login.html',{})
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None: # si si se valido el usuario entonces creamos la sesion
            login(request,user)
            token = Token.objects.get_or_create(user=user)#buscamos o creamos el token del usuario
            #regresamos el token del usuario
            return render(request,'docentes/index.html',{'token':'token '+str(token[0])})
        else:# si los datos del usuario no concuerdan mandamos un error
            return render(request,'docentes/login.html',{'datos_invalidos':'Tu usuario o contaseña son invalidos'})

#para cerrar sesion
@login_required(login_url='docentes:login')  
def cerrar_sesion(request):
    u = User.objects.get(id=request.user.id)
    token = Token.objects.get(user=u.id)#buscamos o creamos el token del usuario
    token.delete()#borramos el token de sesion
    logout(request)
    return redirect('docentes:login')

#para registrar un usuario nuevo

def registrar_usuario(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('docentes:index')
        return render(request,'docentes/registro_usuario.html',{})     
    elif request.method == 'POST':
        allUser=User.objects.all()
        for user_ahutenticate in allUser:
            if user_ahutenticate.username==request.POST['username']:
                return render(request,'docentes/registro_usuario.html',{'noUser':'Usuario ya existente'})

      
        if request.POST['password'] == request.POST['password2'] or request.POST['password2']==request.POST['password']:
            user = User.objects.create_user(username=request.POST['username'],password=request.POST['password'],email=request.POST['email'])

                
        elif request.POST['password'] != request.POST['password2'] or request.POST['password2']!=request.POST['password']:
            return render(request,'docentes/registro_usuario.html',{'password_no_valido':'Contraseña no valida'})
       
        return redirect('docentes:login')

docentes/templates/docentes/actualizacion_informacion.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} Cambio de información {% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login" method="POST">
        {% csrf_token %}
        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h3>Actualizar correo</h3>
        <input  type="email" name="email" placeholder="{{user.email}}">
        <h3>Actualizar nombre de usuario</h3>
        <input type="username" maxlength='20' name="name" placeholder={{user.username}}>
        <button class="login-button" type="submit">Cambiar</button>

        {% if noUser %}
            <p style="color:red">{{noUser}}</p>
        {% endif %}  

        {% if noAcualizado %}
         <p style="color:red">{{noAcualizado}}</p>
        {% endif %}

        {% if email_no_valido %}
            <p style="color:red">{{email_no_valido}}</p>
        {% endif %}
        
        
       

    </form>
{% endblock %}

docentes/templates/docentes/actualizacion_password.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login" method='POST'>
        {% csrf_token %}
        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        
        {% if password_distintos %}
            <p style='color:red'>{{password_distintos}}</p>
        {% endif %}
        
        {% if password_vacio %} 
            <p style='color:red'>{{password_vacio}}</p>
        {% endif %}
        <h2>Solicitar cambio de contraseña</h2>
        <h3>Contraseña Nueva</h3>
        <input  name='password' type="password" placeholder="Contraseña" minlength="5" >
        <h3>Verificar contraseña</h3>
        <input type="password" placeholder="Contraseña"  minlength="5" name='password2'>
        <input class="login-button" type="submit" value="Cambiar Contraseña">    

    </form>
{% endblock %}

docentes/templates/docentes/cambio_password.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login">
        {% csrf_token %}
        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h2>Solicitar cambio de contraseña</h2>
        <h3>Contrasena Nueva</h3>
        <input type="text" placeholder="Contraseña" name='password1'>
        <h3>Verificar contrasena</h3
        <input type="text" placeholder="Contraseña" name='password2'>

        <a href="{% url 'docentes:index' %}"><input class="login-button" type="button" value="Recuperar contraseña"></a>

    </form>
{% endblock %}

docentes/templates/docentes/guardar_informacion_password.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login">
        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h3>Correo electronico</h3>
        <input type="text" value="pedrito"  placeholder="Correo electronico">
        <h3>Contraseña</h3>
        <input type="password" value="12343kdjsnkjdnsjnd3" placeholder="Contraseña">
        <input class="login-button" type="button" value="Guardar cambios">
        <a href="{% url 'docentes:index' %}">Regresar</a>

    </form>
{% endblock %}

docentes/templates/docentes/guardar_informacion_usuario.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login">
        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h3>Correo electronico</h3>
        <input type="text" value="pedrito"  placeholder="Correo electronico">
        <h3>Contraseña</h3>
        <input type="password" value="12343kdjsnkjdnsjnd3" placeholder="Contraseña">
        <input class="login-button" type="button" value="Guardar cambios">
        <a href="{% url 'docentes:index' %}">Regresar</a>

    </form>
{% endblock %}

docentes/templates/docentes/login.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}

{% block navbar%} {% endblock%}

{% block body %}


    <form class="login" action="{% url 'docentes:login' %}" method="POST">
        {% csrf_token %}

        <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h3>Nombre de usuario</h3>
        <input  name="username" minlength="4" type="text" placeholder="Usuario" required>
        <h3>Contraseña</h3>
        <input name="password"   minlength="3" type="password" placeholder="Contraseña" required>
        <input class="login-button" type="submit" value="Iniciar sesión">
        <a href="{% url 'docentes:registrar_usuario' %}">Registrarme</a>

        {%if datos_invalidos%}
            <p style="color:red">{{datos_invalidos}}</p>
        {%endif%}

        {% if no_user %}
            <p style="color:red">{{no_user}}</p>
        {% endif %}
        
    </form>
{% endblock %}

docentes/templates/docentes/perfil_usuario.html
{% extends 'base_html.html' %}
{% load static%}

{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}


{% block body %}


    <form class="login">
        <img src="{% static 'icons/iconUser.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
        <h2 class="text-username">{{user.username}}</h2>
        {% if user.email %}
            <p class="text-correo">{{user.email}}</p>
        {% else %}
            <p class="text-correo">Sin Correo Electronico</p>
        {% endif %}
        <a class="cambiar-datos" href="{% url 'docentes:actualizarUsuario' %}"><h2>Cambiar información</h2></a>
        <a class="cambiar-datos"href="{% url 'docentes:actualizarPassword' %}"><h2>Cambiar contraseña</h2></a> 
    </form>
{% endblock %}

docentes/templates/docentes/registro_usuario.html
{% extends 'base_html.html' %}
{% load static%}
{% block head %}
    <link rel="stylesheet" href="{% static 'docentes/css/style.css' %}">  
{% endblock %}

{% block title %} LAPSOFT Login{% endblock %}



{% block body %}
<form class="login" action="{% url 'docentes:registrar_usuario' %}" method="POST">
    {% csrf_token %}
    <img src="{% static 'icons/logo.svg' %}" alt="logo de la empresa" onclick="window.location='{% url 'docentes:index' %}'">
    
    {% if noUser %}
            <p style="color:red">{{noUser}}</p>
    {% endif %}

    {% if password_no_valido %}
        <p style="color:red">{{password_no_valido}}</P>
    {% endif %}

    {% if email_no_valido %}
        <p style="color:red">{{email_no_valido}}</P>
    {% endif %}
    

    <h3>Nombre de usuario</h3>
    <input name="username" minlength="5" type="text" placeholder="Usuario" required>
    <h3>Correo Electrónico</h3>
    <input name="email" type="email" minlength="8" placeholder="Correo Electrónico" required>
    <h3>Contraseña</h3>
    <input name="password"  minlength="5" type="password" placeholder="Contraseña" required>
    <h3>Confirma la contraseña</h3>
    <input name="password2" type="password" minlength="5" placeholder="Confirmar contraseña" required>
    <input class="login-button" type="submit" value="Registrarme">
    <a href="{% url 'docentes:login' %}">Iniciar sesión</a>

    
    

   
</form>
{% endblock %}