api/urls.py
#urls de la aplicacion de docentes

from django.urls import path
from api import views as v
from docentes import views



#ponemos el nombre de la app para cuando mandemos llamar a las url poner docentes.urls
app_name = 'api'
urlpatterns = [

    path('planeaciones',v.Planeacion_APIView.as_view(),name='planeaciones'),
    path('planeaciones/<str:pk>',v.Planeacion_APIView.as_view(),name='planeaciones'),
    path('clonarPlaneacion',v.PlaneacionClonarView.as_view(),name='clonarPlaneacion'),

    path('buscarPlaneacion',v.Planeacion_APIViewFree.as_view(),name='buscarPlaneacion'),
    path('buscarPlaneacion/<str:titulo>',v.Planeacion_APIViewFree.as_view(),name='buscarPlaneacion'),

    path('favoritos',v.Favorito_APIView.as_view(),name='favoritos'),#para los favoritos
    path('favoritos/<str:pk>',v.Favorito_APIView.as_view(),name='favoritos'),#para los favoritos

    path('actividades',v.Actividad_APIView.as_view(),name='actividades'),#para los favoritos
    path('actividades/<str:pk>',v.Actividad_APIView.as_view(),name='actividades'),#para los favoritos
    path('actividadesFree',v.Actividad_APIView.as_view(),name='actividadesFree'),#para los favoritos sin logearse
    path('actividadesFree/<str:pk>',v.Actividad_APIView.as_view(),name='actividadesFree'),#para los favoritos sin logearse

    path('obtenerComentarios',v.Comentario_APIViewFree.as_view(),name='obtenerComentarios'),
    path('obtenerComentarios/<str:pk>',v.Comentario_APIViewFree.as_view(),name='obtenerComentarios'),
    path('comentarios',v.Comentario_APIView.as_view(),name='comentarios'),
    path('comentarios/<str:pk>',v.Comentario_APIView.as_view(),name='comentarios'),


]

docentes/urls.py
#urls de la aplicacion de docentes

from django.contrib import admin
from django.urls import path
from docentes import views

#ponemos el nombre de la app para cuando mandemos llamar a las url poner docentes.urls
app_name = 'docentes'

urlpatterns = [
    path('',views.index,name='index'),
    path('login',views.login_user,name='login'),
    path('registrarse',views.registrar_usuario,name='registrar_usuario'),
    path('cerrarsesion',views.cerrar_sesion,name='cerrar_sesion'),
    path('actualizarPassword',views.actualizarPassword,name='actualizarPassword'),
    path('actualizarUsuario',views.actualizarUsuario,name='actualizarUsuario'),
    path('crearPlaneacion',views.crearPlaneacion,name='crearPlaneacion'),
    path('favoritos',views.favoritos,name='favoritos'),
    path('misPlaneaciones',views.misPlaneaciones,name='misPlaneaciones'),
    path('perfil',views.perfil,name='perfil'),

]

planeacion_docente/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('docentes.urls')),
    path('api/',include('api.urls'))
]

templates/base_html.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">

    <link rel="icon" href="{% static 'icons/logo.svg' %}">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">

    <title>{% block title%} {% endblock %}</title>
    <style>
        .text-user::after{
            content:'{{user.username}}';
        }
    </style>


    {% block head %}
    {% endblock %}
</head>
<body id="body">
    {% block navbar %}

    <nav class="nav"> 
        <div class="nav-icon">
            <img src="{% static 'icons/logo.svg' %}" alt="logo aplicacion" onclick="window.location='{% url 'docentes:index' %}';">
            <a class="center-ex no-decoration text text-marca" href="{% url 'docentes:index' %}"></a>
        </div>
        <div class="nav-item">
            {% if user.is_authenticated == False %}
            <a class="center-ex no-decoration text" href="{% url 'docentes:login' %}">Iniciar sesión</a>
            <a class="center-ex no-decoration text" href="{% url 'docentes:registrar_usuario' %}">Registrarse</a>
            {% else%}
            <a title="Crear planeación" class="item center-ex no-decoration text text-crear" href="{% url 'docentes:crearPlaneacion' %}"><img src="{% static 'icons/create.png' %}" alt="icono planeacion"></a>
            <a title="Favoritos" class="item center-ex no-decoration text text-favoritos" href="{% url 'docentes:favoritos' %}"><img src="{% static 'icons/iconLikeDark.svg' %}" alt="icono favoritos"></a>
            <a title="Mis planeaciones" class="item center-ex no-decoration text text-mis-planeaciones" href="{% url 'docentes:misPlaneaciones' %}"><img src="{% static 'icons/iconPlan.svg' %}" alt="icono planeacion"></a>
            <a title="Perfil" class="item center-ex no-decoration text text-user" href="{% url 'docentes:perfil' %}"><img src="{% static 'icons/iconUser.svg' %}" alt="icono usuario"></a>
            <a title="Cerrar sesión" class="item center-ex no-decoration text cursor-pointer text-cerrar-sesion" onclick="cerrarSesion()"></a>
            {% endif%}
        </div>
    </nav>

    {% endblock %}
    {% block body %}
    {% endblock %}
    <script>
        /**
        para cerrar la sesion borrando el token de local storage y redireccionando para que se borre la sesion
        */
        function cerrarSesion(){
            localStorage.clear();//borramos los tokens del navegador
            window.location.replace('{% url 'docentes:cerrar_sesion' %}');//redireccionamos para que se cierre la sesion
        }
    </script>
</body>
</html>